# Generated by Django 2.2.14 on 2022-05-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('color', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE'), ('GREEN', 'GREEN'), ('PINK', 'PINK'), ('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('GREY', 'GREY')], default='DEFAULT', max_length=100)),
                ('gender', models.CharField(choices=[('N/A', 'N/A'), ('Unisex', 'Unisex'), ('Male', 'Male'), ('Female', 'Female')], default='Unisex', max_length=100)),
                ('age', models.CharField(choices=[('N/A', 'N/A'), ('Children', 'Children'), ('Adult', 'Adult')], default='N/A', max_length=100)),
                ('currency', models.CharField(blank=True, default='Ksh', max_length=120, null=True)),
                ('inventory', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('stars', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('3', '1')], default='5', max_length=100)),
                ('caption', models.CharField(blank=True, max_length=120, null=True)),
                ('review', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('text', models.CharField(blank=True, max_length=220, null=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Product')),
            ],
        ),
    ]
