# Generated by Django 2.2.14 on 2024-03-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productfeatured',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='productfeatured',
            name='text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='caption',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('3', '1')], default='5', max_length=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='age',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Children', 'Children'), ('Adult', 'Adult')], default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='gender',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Unisex', 'Unisex'), ('Male', 'Male'), ('Female', 'Female')], default='Unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
